#!/bin/sh

echo "Running fmt..."
gofmt -s -w .

echo "Running lint..."
golangci-lint run
if [ $? -ne 0 ]; then
  echo "Lint failed"
  exit 1
fi

echo "Running tests..."
go test -race ./...
if [ $? -ne 0 ]; then
  echo "Tests failed"
  exit 1
fi

echo "Pre-commit passed"
